### ISSUE TITLE
New Gold Mailing Button - "Banker"

### ISSUE THREAD

**Issue by Fakevox** [Icecrown-Community/ICC-Member-Website-Public#100]
New button for Gold Mailing "Banker"

Click this button to automatically copy the bankname-realm for the server you're making payment on. 

![image](https://user-images.githubusercontent.com/78853011/107792977-aef2f700-6d4d-11eb-9037-82bf96a2f024.png)

I know there's the WA but this is a Quality of Life enhancement that reduces error.

**Comment by Fakevox** [comment]
I don't think this mspaint job will fool you this time @iElsha :)

**Comment by TheAmazingTyr** [comment]
duplicate of #62

**Comment by Fakevox** [comment]
Hodor.
