### ISSUE TITLE
Update the function of "Copy Customer Name"

### ISSUE THREAD

**Issue by Fakevox** [Icecrown-Community/ICC-Member-Website-Public#101]
When clicking the customer name have it also include and copy a message.

"/w Name-realm Message"

This saves us time in writing or copy pasting messages and means we all use the same professional message etc.

For Example Dejnaa uses "Hello my friend! I am the gold collector for todays boost - I am just checking that you are online - you will be invited shortly."

You could also have this message change depending if 100% paid or not.

If payment = 0% THEN message - Collecting the payment
If payment =>1% & less than 100% Then message - The remaining payment
If payment = 100% - Hey I'm organising the invites, are you available? :)

Etc etc

Thoughts?

**Comment by TheAmazingTyr** [comment]
overcomplicating merger of #58 and #60 , would overload the amount of buttons on each card, wouldn't it be easier to just type /w, paste name, say hi, open next chat box, copy down your introduction from intro note of #60 and go that way? 
remember that we're not using the name copy just as a way to whisper people, but also to place them in our personal sheets, or passign names to guilds who dont want to have us sitting in their grps, i dont want my intro message in each cell of my spreadsheet or in every 2nd message i send to a guild

**Comment by Fakevox** [comment]
Let's take a step back then and see if there's a way to remove the requirement for a spreadsheet of your own. :)

**Comment by Fakevox** [comment]
E.g. the Version 3.0 of the website did the following.

You could login to your own GC page and see all your outstanding collections across all raids etc.
You could sort by realm/advertiser/date
It would also total on realm by advertiser. E.g. Certificate owes me 500k for runs X Y Z and James owes me 250k for A and B.

**Comment by ICCDesi** [comment]
I am closing this since it's a feature that we plan for the Addon we are currently working on.

Good suggestion though.
