### ISSUE TITLE
Suggestion: Add "Balance" realm if boost is getting paid with balance. 

### ISSUE THREAD

**Issue by TheAmazingTyr** [Icecrown-Community/ICC-Member-Website-Public#102]
Newly, it's sheerly the GC's job to fix balances. i tend to miss them and then ask the advs for the gold. while yes i am a pepeja, the above could be decently good? maybe not implement it as a payment realm within dropdown menu, isntead have a checkbox next to payment realm which will be exclusive with each other.

**Comment by Dejnaa** [comment]
Elsha, would this be hard to implement rather sooner then later? It is not suposed to have any "different" function then other realms, only show on booking its balance so adv/GC/RL sees it

**Comment by Papa2324** [comment]
* Papa added the **Urgent** label *

**Comment by iElsha** [comment]
@Papa2324 automatic deduction will not be done.

**Comment by TheAmazingTyr** [comment]
it's not supposed to auto-substract, it's just clarity for GCs and banking.

**Comment by iElsha** [comment]
Implemented
