### ISSUE TITLE
Have all advertisers do !Pset and have a pseudo name removing the -realm of their name.

### ISSUE THREAD

**Issue by Fakevox** [Icecrown-Community/ICC-Member-Website-Public#103]
One of the problems I'm having whilst doing the mailing of gold is that You constantly see the name-realm of the advertiser straight above the customer. From time to time this has caught me off guard and resulted in a boo boo.

If we make them all have the Pseudo name like Sefildh has here for example, it would remove the opportunity for this to happen.

![image](https://user-images.githubusercontent.com/78853011/107980736-ad793700-6fb8-11eb-9973-17d1d03b112e.png)

Also means that if they all have [Adv] in their name it's easier to see them on Discord for customers etc.

Thoughts?

**Comment by iElsha** [comment]
Can you open it there: https://github.com/Icecrown-Community/Icecrown-Precious-Bot-Public/issues
Then close here pls

**Comment by Fakevox** [comment]
I can when I see it 3 weeks later KEKW
