### ISSUE TITLE
Booster sign-up note

### ISSUE THREAD

**Issue by IndigoICC** [Icecrown-Community/ICC-Member-Website-Public#106]
It would be amazing if boosters, who sign up, had the ability to add a note for the raid leader - "I'm unsaved/saved". This will save time for the Raid Leader when looking for VIP traders. 
https://gyazo.com/d48170fb6e798ad16657a6ad522a78ee

**Comment by IndigoICC** [comment]
Giving this a bump

**Comment by ICCDesi** [comment]
@Bgabor997 can maybe do this quick?
