### ISSUE TITLE
RL view - Can't edit anything as Gold Collector

### ISSUE THREAD

**Issue by Wanhedaa** [Icecrown-Community/ICC-Member-Website-Public#107]
![image](https://user-images.githubusercontent.com/77633500/108825189-02253f00-75c3-11eb-9630-0cccb5c0b8cd.png)

I can't edit anything after it is set from the "running" phase to the "RL view" phase.

This isn't a big deal, unless an overbook happens. For example, one night the curve run was already overbooked about 1.5 hours before the end of the raid, the raid leader changed the status to "**_RL view_**" so that others could not add new customers to the current raid, but during that time someone might not shows up (therefore must be canceled) + the gold collector has to rewrite the notes for the other customers so that he can take notes for himself aswell, etc.

The raid leader has to reopen the raid - possibly risking a "overbook" chance. <- this happend 1 night, where the boosters finished the boost at 01:30 instead of 00:00 because of the overbooks in between 2 "reopening"

**Solution:**
Allow the assigned _gold collectors_ to edit the customer info / cancel a customer in RL view.

**Comment by Dejnaa** [comment]
+1000000

**Comment by Dejnaa** [comment]
I think this is just a permission thing? Can we make so GCs can still edit the bookings in RL view (step before GoldMailing). 
THey would do it after the raidlead put it to RL view so advertisers cant book anything else - while the GC normally is still updating the notes, gold collected ect

**Comment by ICCDesi** [comment]
The raid shouldn't go in "RL" phase unless the gold collector approved it. 

There is nothing to be fixed here as the solution is already there.
