### ISSUE TITLE
Advertiser cut in raids

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/ICC-Member-Website-Public#110]
Last week I had 4 people asking me if they can give away their cut to give their customer a lower price - for Raids.

This made it a bit difficult, as in order for the raiders and the advertiser to get the correct cut we have to add the gross price to the raidbooking, and then know that the buyer is supposed to pay the nett amount (-adv share) - send in less then the booking says and Indigo needs to alter something in the raid on his side. Think we also had to deduct the amount from the advertiser since he would get it from the raid so it became +/- 0

Can we add a checkbox that the advertiser can check that will exclude them from getting a cut from that booking?

Then they can book the payment amount that the customer is supposed to pay, everyone gets correct cuts and the booking corresponds with the mail from the GC - currently we dont have that many cases, but it does give a lot of extra manual work and also is very easy to do mistakes. 

Thank you

**Comment by iElsha** [comment]
> Can we add a checkbox that the advertiser can check that will exclude them from getting a cut from that booking?

Yes but in the future

**Comment by Dejnaa** [comment]
Nobody has asked for this since that raid, so I am gonna assume that until further notice the interest is so low that it is irrelevant. 
I will close this as we have more important topics to work on
