### ISSUE TITLE
Creating raids without RL/GC

### ISSUE THREAD

**Issue by IndigoICC** [Icecrown-Community/ICC-Member-Website-Public#111]
In order to create a raid via the website; there has be to an assigned Raid Leader and Gold Collector. I would like for this to be optional; with the aim of getting boosters signed up ASAP. 

Obviously the RL/GC would be assigned before the run is supposed to start; which would be done via the 'Edit' function.

**Comment by iElsha** [comment]
For simplicity purposes, we'll use @precious for the moment that won't be worked regarding the prior list

**Comment by Dejnaa** [comment]
I guess this is fixed in a way?

**Comment by IndigoICC** [comment]
We're using Precious as an assigned RL/GC for the time being
