### ISSUE TITLE
What bosses the raid offers and how many - Visialisation

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/ICC-Member-Website-Public#113]
Hey - Mythic raid and you see no info unless you click booking and then see:

![image](https://user-images.githubusercontent.com/77668716/114061363-a541c780-9896-11eb-8897-5a94af925da5.png)

This is shit. Pardon my french - I dont mean the website ofc, I mean the way the information is lacking.

Solution:
Put the bosses on the top part and show how many the raid offers - let it also deduct the boss-count with each booking (not for curve shifts)

![image](https://user-images.githubusercontent.com/77668716/114061860-2d27d180-9897-11eb-85e3-f6e1c8e895d9.png)

This is also what ChineseDH is crying about all the time asking for sheets. For this particular thing I totally agree that we need a way to see how many bosses they can provide, by looking on the overview - and not having to message the guild reps every time... I totally can take DMing for VIPs, but let us at least have the boss count. They can change it when they get bookings somewhere else. 

We lost a 10/10+5VIPs today, cause no guild was doing 10/10 to start with. Found out by DMing them - really inofficiant and time wasting for all our advertisers. We could then change Mythic Macros to "Only offering Mythic Shriekwind, Houndmaster, Councile and Sludgefist tonight".

**Comment by Papa2324** [comment]
Hey, I've opened this issue days and days ago in the council section - change is coming soonTM :)

**Comment by ICCDesi** [comment]
@iElsha :)

**Comment by Dejnaa** [comment]
Yes please, this is really needed..... 

If Elsha also can make so you cant book a particular boss if the count is 0 then overbooking in HC/Mythic would be non-existant
Only issue left would be curve (thats for another day I guess)

**Comment by iElsha** [comment]
**Advertiser view**
![image](https://user-images.githubusercontent.com/38140638/114421505-a7b56180-9bb5-11eb-9c07-c6178b2b6d82.png)

**RL & GL view**
https://user-images.githubusercontent.com/38140638/114421554-b56ae700-9bb5-11eb-859a-2b2364f952f6.mp4

**Comment by iElsha** [comment]
We might change the red color, other than that it's :ok: 

Do we also need this for Heroic raids @Icecrown-Community/icc-raid

**Comment by ICCDesi** [comment]
Can be helpful for heroic as well. Since you're doing it, might as well implement it there.

**Comment by IndigoICC** [comment]
I don't see a point of not having it; even if we aren't going to use it for Heroic right away. Heroic is incredibly dynamic; so there isn't really a "cap" per say.

**Comment by iElsha** [comment]
We'll allow heroic for next tier, it's not a lot of code to change for this and disable when we don't need it anymore

**Comment by iElsha** [comment]
Implemented
