### ISSUE TITLE
Sends you to bottom of list

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/ICC-Member-Website-Public#117]
If you open a raid, and scroll down and then click Back it sends you to the bottom of the website (with all raid and dates).

Its really annoying. Especially in the start of a new month where we have all raids set up.

Can this be changed to that it gets you back to where you were before you clicked the specific raid?

**Comment by Dejnaa** [comment]
Is it possible to fix this?

**Comment by ICCDesi** [comment]
Low priority but I guess it can be done with:

> #31 Update the raid data in nearly real time

**Comment by iElsha** [comment]
Enable scrolling to top when moving to another page

**Comment by Dejnaa** [comment]
Is it possible to make it so if you press "back" it goes back to where you were and not top/bottom of the page?

Most websites has this

**Comment by Dejnaa** [comment]
@Bgabor997 do you know? Just checking and if its not possible I will just close the ticket

**Comment by iElsha** [comment]
Yes this is possible but need some works

**Comment by Wanhedaa** [comment]
Can we also add a short button to scroll up on the web at bookings also? we have to check the available spot each curve, for that you have to scroll down. But to book it, you have to scroll up (i know we can use the original browser short scroll, but not everyone is a tech genious)

![image](https://user-images.githubusercontent.com/77633500/131009671-f55568b3-29f6-4f8a-913d-0d13e431e0dc.png)

**Comment by DJDajn** [comment]
1

**Comment by Bgabor997** [comment]
This was deployed at 2021.10.02
