### ISSUE TITLE
raid deleted - no date shown

### ISSUE THREAD

**Issue by Wanhedaa** [Icecrown-Community/ICC-Member-Website-Public#125]
I, personally have 5-6 curves /week (if not more) and if a raid is getting deleted, i don't know which one got. 

I get this message from Gluth, but it informs me only about deleting, not about which one is getting deleted. Ofc i can ask indigo or  the raidleader which one is it, but i think it would be easier just edit the message with a date :D 

Currently we get this: 
![image](https://user-images.githubusercontent.com/77633500/124360645-37096880-dc2b-11eb-909a-685589027137.png)

If i get choosen for curve, i get this 
![image](https://user-images.githubusercontent.com/77633500/124360656-4b4d6580-dc2b-11eb-91c9-e4097d489d9b.png)
it shows which raid is it without clicking on the link (as if it's deleted, i don't have any link to click anyway)

**Comment by DruidEmmaNielsen** [comment]
I personally also had love to have an "Archieve" section.

So if a Raid gets deleted, or cancelled. we can view the raid under a different tab / direct link. -  This helps in few cases where one either is Gold Collector and did eairly collects, or just for overall having a better overview of the situation.

**Comment by Dejnaa** [comment]
We obviously have this working for the other type of messages from gluth, cant you just copy that code from them and insert into the Deleted Raid message? @iElsha 

These have the dates in the end of the message:
Raid Approved
Raid Submitted
Raid GC changed
Booking Edited
Booking Deleted

This do not:
Raid Deleted

**Comment by Dejnaa** [comment]
@Bgabor997 Do you know an estimate to fix this?

**Comment by iElsha** [comment]
30 minutes

**Comment by Dejnaa** [comment]
@Papa2324 please add severity to this

**Comment by Papa2324** [comment]
@Bgabor997 Can you blast this quick when you find 20 30min? <3

**Comment by Bgabor997** [comment]
This was deployed at 2021.10.02
