### ISSUE TITLE
[PvP] To fetch or not to fetch, that is the question.

### ISSUE THREAD

**Issue by FyneIcc** [Icecrown-Community/ICC-Member-Website-Public#129]
First of all, thanks a lot for good job @iElsha , sorry for being difficult...

> Check pvp and armory might not be up to date based on the spec, item set or whatever. It's still good for the adv to double check. 
The only use case would be to simplify adv life, which is great but not a priority right now. If you can elaborate more, open an issue on <https://github.com/Icecrown-Community/ICC-Member-Website-Public/issues/>

I've made this list with the assumption that the client have not recently faction changed, renamed or anything similar.

* If advertiser writes in right Name-Realm they will get right faction. Easy fetch.
* The class obviously will always be static if you write in the right Name-Realm. Easy fetch.
* And ilvl, within reasonable amounts, isn't to important. So having slightly wrong ilvl showing isn't bad. A rough estimate good enough. Easy fetch.
It's more about the %versatility that's important, but that's not possible to fetch if client doesn't wear the PvP gear when updated. 

* Specialization is good to not have fetched, as that's heavily swapped around depending on client. Do not fetch, ask client what he prefers to play.
* Covenant is something not swapped out to frequently, but is very important to have it right. Do not fetch. Advertiser ask what covenant client is.
* Don't fetch current rating, very often not updated.

**Comment by infinitypros** [comment]
hey, we would not work on this issue atm as its really a very minor update
