### ISSUE TITLE
Raids being submitted. 

### ISSUE THREAD

**Issue by ICCDesi** [Icecrown-Community/ICC-Member-Website-Public#13]
We have issues with raids when we submit them. It's the second time that this have happened. It looks like it happens with Curve runs.

**Raid ID**: 796092449394131091
**Raid ID**: 795658592849100804

Side note: The raid with the ID 795658592849100804 got bugged as we clicked ''submit'' . Unknown information for 796092449394131091.

**Comment by ICCDesi** [comment]
Another one. Can we please prioritise this?

**Raid ID:** 797211158498115584

**Comment by Papa2324** [comment]
![image](https://user-images.githubusercontent.com/77280335/104187918-c53d2880-5418-11eb-90d5-1d3a94b55ad3.png)

Certain pots/customers get submitted multiple times (as noted) and some arent even getting submitted. The raid takes multiple minutes to get submitted (unsure if normal, waited like 5-7 minutes for the submit to be done even on pots with just 2 customers)

**Comment by iElsha** [comment]
@ICCDesi @Papa2324 this is fixed thanks to https://github.com/Icecrown-Community/ICC-member-website/pull/71 and https://github.com/Icecrown-Community/ICC-member-website/pull/70
