### ISSUE TITLE
Not bookable when 0/0

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/ICC-Member-Website-Public#132]
Please make it not possible to book anything if the raid has 0/0 customers. 

Thus would help when we have guilds like Meldteam that put up 100 raids per week and dont even know if they will be  boosting them until the day before.

**Comment by Dejnaa** [comment]
Just make the book button non clickable if the customer amount is 0/0 

(Curtesy to Highlife)

**Comment by Dejnaa** [comment]
@Bgabor997 would this be much work?

**Comment by Bgabor997** [comment]
Nope, 30min, **with tests**

**Comment by Dejnaa** [comment]
@iElsha Please approve

**Comment by iElsha** [comment]
Approving what?

**Comment by Dejnaa** [comment]
@iElsha again, reading above 2 comments would answer your question and save both you and others time.

Acording to Gabor it would take 30min (inc tests) to get this issue done. As you gotta approve, I ask you to approve.

**Comment by Papa2324** [comment]
I approve :)

**Comment by Dejnaa** [comment]
@Papa2324 please add severity.

**Comment by Dejnaa** [comment]
sorry, I mean upp the severity

**Comment by Papa2324** [comment]
@Bgabor997 I suppose we can add this to the basket :kekLeo:

**Comment by iElsha** [comment]
I don't see the emergency point of this feature downgrading to 4

**Comment by Dejnaa** [comment]
This would also be helpful when we cancel raids that already has bookings. So the advs can rebook their customers but other advertisers cant book anything new.

**Comment by Bgabor997** [comment]
implemented and deployed 2021.10.14
