### ISSUE TITLE
Block "Delete booking" when within 2h of raidstart.

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/ICC-Member-Website-Public#133]
We have advertisers who delete their bookings if their customer is MIA or cancells in the last second. 

We are suposed to collect a deposit for this but if the advertiser removes the booking we dont know who to take the deposit from. 

If they cant cancel they will have to just edit the price to 10% of the original price that will be the deposit payment. 

Therefor I would ask to block the delete button within 2h from raidstart. (Not for Curve shifts)

**Comment by Wanhedaa** [comment]
i think 2 hours is much, anything can come up and we could get any other customer instead of his in like 30 mins. I like your idea, but with like 1 hour instead of 2

**Comment by Dejnaa** [comment]
1h is fine aswell, I just said 2h as its reasonable to get a replacement within 2h - 1h can be a little short

**Comment by Dejnaa** [comment]
@ICCDesi @Papa2324 @Tueri 

Opinions?

**Comment by Efthymios-Papakostopoulos** [comment]
Not a bad idea at all. Sorry i might have missed this.

It is possible, i would like it and i would even suggest increasing that time frame

**Comment by disstressed** [comment]
One hour is better, most of the time it's easy to find a last minute customer even in 30 minutes. However, wouldn't it cause an issue of "1 less customer that run, even with deposit", an advertiser  deleting the booking at least gives the other advertisers a chance to book someone, and in this case , they won't even probably be able to remove so keeping track of how many customer slots available might be an issue

**Comment by Dejnaa** [comment]
@Bgabor997 how long do you think this feature would take to make? If even possible?

**Comment by Bgabor997** [comment]
doable, ofc, i would say 1,5 hour with the tests

**Comment by Dejnaa** [comment]
@iElsha Please approve

**Comment by Dejnaa** [comment]
@iElsha This issue can be fixed by putting in 1,5h (inc tests) according to Gabor - please approve that he does this.

**Comment by infinitypros** [comment]
locking 1 hour before the riad will be enough, its on the implementing list now

**Comment by Bgabor997** [comment]
this is implemented and deployed today
