### ISSUE TITLE
Change to fixed timeslots and limited amount of customers (like for Mythic raid)

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/ICC-Member-Website-Public#134]
We have a reoccuring issue of advertisers not knowing when to book their KT, Sylv, KT+Sylv. We had the same problem before with Nathria. My suggesstion is if we can program so you dont get to choose "any time" when you book to the shifts, but to have fixed spots - prefferable also with fixed amount of customers, so they can EASY book without being afraid to book to much.

Example - Now we have a "process time" of 40min for KT&Sylv, Before we had 30min for SLG+Sire.

If there is an option for Raid Lead to mark the [Minutes between each shift] and [amount of bosses per shift] then when someone want to book for example KT+Sylv but we have already all Sylv booked that timeslot it would tell them "Sorry, this timeslot if fully booked for the selected bosses, please pick the next one".

And example how it could look when making a new Last 2 bosses event: (its only an example, not suggesting this is how it has to be)

![image](https://user-images.githubusercontent.com/77668716/127862931-afec0ebd-83d3-4809-b106-c80734a0f324.png)

And this is how it could look for the advertiser: (its only an example, not suggesting this is how it has to be)

![image](https://user-images.githubusercontent.com/77668716/127864317-4d133c9f-37b8-42ee-b062-152e6b8e1d83.png)

**Comment by Wanhedaa** [comment]
I'm pretty sure i suggested this already, but got closed. Let's hope they will do it this way tbh <3  Because waking up for 20 message about "please fix the bookings" is like a hell. Amazing idea pls do it <3

**Comment by Dejnaa** [comment]
Oh and in case someone asks - I was NOT thinking the dropdown list should update in real time. Was thinking that when you open the booking page it will load the info about what slots are still not fully booked. If someone books while you are typing all info the time slot would of course not change. But then when you press book  thats when it checks if the spot is still available - and if not gives you the "please choose a different time".

**Comment by Dejnaa** [comment]
@Bgabor997 what do you think about this?

**Comment by Bgabor997** [comment]
The bigger thing here, is we have different times between KT - Sylvanas and Sylvanas KT, so we have to set each boss "duration" this will take 5-6 hours at least, with the testing

**Comment by Dejnaa** [comment]
Sounds reasonable, is there anything I can do to help make the time less so that this could be upped on the "waitlist"? :)

**Comment by Dejnaa** [comment]
@ICCDesi @Tueri 

What do you think? Considering any other projects going on right now (that I may not know about) would you say we would like this to be dealt with coming weeks? This would really help both in planing the boost (raidlead), booking the customers (adv) and to some degree also help GCs not having to reschedule and contact customers that are offline when raid is preforming bit better then on avrage.

**Comment by Bgabor997** [comment]
I'm working on this rn, we have some sketch for it, need some more time, but a whole new system will come for this soon
![image](https://user-images.githubusercontent.com/25648979/134903864-b344dd18-2fd8-4afa-a923-02d45e4514f4.png)
![image](https://user-images.githubusercontent.com/25648979/134903880-696570fc-008a-4a24-9a61-bbbc05299b81.png)

**Comment by Bgabor997** [comment]
This was deployed at 2021.10.02
