### ISSUE TITLE
Last 2 - Normal or Heroic? (or Mythic down the line?)

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/ICC-Member-Website-Public#136]
Could we make it so we can see a different between Normal Last 2 or Heroic Last 2 bosses? (later maybe also mythic?)

Please guess which ones are normal and which ones are heroic:

![image](https://user-images.githubusercontent.com/77668716/128560365-f8bd517f-e09f-498a-ae6a-2888dcea73a7.png)

**Comment by Dejnaa** [comment]
@Bgabor997  could this not be fixed by adding 1 new "Raid Service" to the Raid Settings?
Just cpoy the Last 2 - Call it Last 2 (NM)
Rename other Last 2 to Last 2 (HC)

Same everything else (cuts blablablabla)

Job done?

**Comment by Bgabor997** [comment]
hmmm, we still have normal last 2? o.O

**Comment by Wanhedaa** [comment]
Alliance has it, but its most likely for the next season i guess.

**Comment by Dejnaa** [comment]
Yes we have and we will have next season aswell

**Comment by Dejnaa** [comment]
Nice Normal was just removed on pricelist this can wait till we start Season 3 - will reopen then
