### ISSUE TITLE
automate the note expand session 

### ISSUE THREAD

**Issue by Wanhedaa** [Icecrown-Community/ICC-Member-Website-Public#139]
Since we have the timestamps, it shows always that we have some note each bookings at curve. 
![image](https://user-images.githubusercontent.com/77633500/131190152-c69888ba-22fc-4d90-9ec2-dddd5146fe5b.png)

Now i always open all of them before even start to collect, so i don't miss any interesting bookings like those: 
![image](https://user-images.githubusercontent.com/77633500/131190270-4fd6b9dc-60d3-4e1f-8339-d410d8e1ddd2.png)

Can we do that it opens all automaticly after each refresh ? Atleast on GC tab (at a simple collecting from customer would be also helpfull if he pays on different character or half other realm etc.

**Comment by Bgabor997** [comment]
Solution here: in GC view make notes expanded by default

**Comment by DJDajn** [comment]
This has been implemented.
