### ISSUE TITLE
Warcraftlogs link

### ISSUE THREAD

**Issue by nGabrr** [Icecrown-Community/ICC-Member-Website-Public#143]
So I was thinking about having a direct link next to the booster signup when choosing your roster for the raid, like we got the check-pvp one in discord. This'd make easier log-checking a bit imo.

**Comment by Wanhedaa** [comment]
Does it really matter? If they are accepted as booster, don't you think, they should have a chance to get into a boost? Else just don't accept everyone

**Comment by nGabrr** [comment]
It could be helpful for new RL's imo.

**Comment by Hurstilol** [comment]
> Does it really matter? If they are accepted as booster, don't you think, they should have a chance to get into a boost? Else just don't accept everyone

Well if they are accepted on their main that doesnt make them a good pick on their alts, we have a lot of boosters that play good on their mains and then they think "why dont i just boost on my garbage alt".
A direct link to their wcl page would be a nice thing to have. Obv its not a thing we desperatly need or anything but it would save some time and if its not too much work for our beautiful devs it would be nice to see this getting added.

**Comment by iElsha** [comment]
Put minor label as it's not vital but is an enhancement, please comment if you need a higher priority.

**Comment by nGabrr** [comment]
Since we are talking about small enhancements, we could have some kind of favorite button, so we could mark the boosters we know well and are blasters. They sign up, have a mark next to their names as a sign, and thats it. I dont think i should open a new thread for this.

**Comment by Tueri** [comment]
> Since we are talking about small enhancements, we could have some kind of favorite button, so we could mark the boosters we know well and are blasters. They sign up, have a mark next to their names as a sign, and thats it. I dont think i should open a new thread for this.

New suggestions/issues should be posted separately, they cannot be handled from the comment section of another.

**Comment by Tueri** [comment]
Bump on this one, it's becoming increasingly necessary to check chars pre-roster building. Either hyperlink from clicking name (instead of copy-paste) or new button as above.

**Comment by DJDajn** [comment]
This was added a few days ago.
Can you close @Bgabor997? ^^
