### ISSUE TITLE
Favorite marker for raid boosters

### ISSUE THREAD

**Issue by nGabrr** [Icecrown-Community/ICC-Member-Website-Public#145]
So I was thinking that we could have some kind of favorite button next to boosters name, so that way you could mark the boosters you know personally, and perform well. With this, if one of them signs up you wont have to look after his logs/performance.

**Comment by infinitypros** [comment]
I know there is some nice player each leader always pick on their roster as it reduces the risk of any fail pulls but having a mark on them so it's easier to pick them is a no.
 
 we wont like to enforce something like that, as we don't want to end up with having each leader having his own team boosting together every time and be unfair to other boosters.

**Comment by Dejnaa** [comment]
@nGabrr Would you please close this ticket? ^^
