### ISSUE TITLE
Capitalized letter

### ISSUE THREAD

**Issue by FyneIcc** [Icecrown-Community/ICC-Member-Website-Public#146]
Have website set normally capitalized to where check-pvp.fr actually works, advertisers more often than not forget to use ''shift'' while writing the name of client.

Example of Ohdear, he correctly wrote the name, but without being capitalized the check-pvp.fr link wont work.

![image](https://user-images.githubusercontent.com/77837483/126864687-3b800860-5fc2-4771-88e3-c3022661f5cc.png)
![image](https://user-images.githubusercontent.com/77837483/126864716-46ac7a21-8292-4e7d-bd08-bf3080e17b5a.png)
![image](https://user-images.githubusercontent.com/77837483/126864749-6d3f82f0-e2ed-41f5-a743-cdd82754990e.png)

**Comment by iElsha** [comment]
Approving what?

**Comment by Dejnaa** [comment]
@iElsha if you would read 2 comments above you would see. This Issue can be fixed by 5 min of work according to Gabor, and since you need to approve work he is doing I asked you to approve him dealing with it.

**Comment by Papa2324** [comment]
I approve :)

**Comment by iElsha** [comment]
@Bgabor997 update the capitalized letter on the website for the bot to have the correct data

**Comment by Dejnaa** [comment]
@FyneIcc This is deployed, you can close the ticket :)
