### ISSUE TITLE
Change #apply-to-icc-eu to #become-a-booster

### ISSUE THREAD

**Issue by Highlifez** [Icecrown-Community/ICC-Member-Website-Public#149]
I think this would significantly reduce the amount of booking tickets that get opened to ask about how to become a booster and be straight forward, as you can only apply to become a booster (or adv, see below) anyway. 

I know that channel also tells you where to apply to become an advertiser, either just leave that in, or make a #become-an-advertiser channel further down where the bookings are.

**Comment by Highlifez** [comment]
In addition to that, you could put in a link to #✉️open-a-ticket if they have any specific questions on how to become a booster.

A lot of us advs are not boosters/recruiters/managers and won't be able to answer their questions anyway.

**Comment by Dejnaa** [comment]
@ICCDesi  should be able to fix? :)
