### ISSUE TITLE
Show guild cut on website

### ISSUE THREAD

**Issue by Wanhedaa** [Icecrown-Community/ICC-Member-Website-Public#157]
![image](https://user-images.githubusercontent.com/77633500/135732586-6c838dd9-d88f-4a96-bacb-555aae5636b6.png)

With the new feature we can see the booster cut as an inhouse booster. But how about the guilds? It could be easily possible to calculate with "total pot" x "guild cut in %" 

Its not a biggie but would be helpfull. 
Love you Gabor <3 
![image](https://user-images.githubusercontent.com/77633500/135732648-d39ae6ce-9a71-4742-84d4-74549d13aad0.png)

**Comment by DJDajn** [comment]
![image](https://user-images.githubusercontent.com/4588530/135732894-4cc61a09-30c8-4154-b629-7065d379ac98.png)

**Comment by DJDajn** [comment]
This was added a few days ago.
Can you close @Bgabor997? ^^
