### ISSUE TITLE
Booster cut shown in Gluth message

### ISSUE THREAD

**Issue by Wanhedaa** [Icecrown-Community/ICC-Member-Website-Public#158]
![image](https://user-images.githubusercontent.com/77633500/135758039-459138f5-babe-4d55-9eaf-c11a5c048748.png)

When the run is submited we get a message about the participants, the total pot, the date and everything but Booster cut. Can we have it? ^^ 

I pasted the "raidleader cut extra" there aswell in case the RL-s want to see their cut in the submission.

**Comment by Bgabor997** [comment]
implemented and deployed 2021.10.14
