### ISSUE TITLE
Suggestion:  Click  Advertiser names for User Id's   

### ISSUE THREAD

**Issue by DruidEmmaNielsen** [Icecrown-Community/ICC-Member-Website-Public#159]
Okey so for balance payments the easist to do is simply doing  the following command

!ihp "<@runid>" amount RaidID: xxxxxxxxxxxx 

this makes it so that management merely has to copy paste, but for us gold collectors, we have to find the name and right click + copy id before we can do this, so I wanted to add another feature to the website.  Now i am aware it is not always the advertisers balance we are talking about, but to my experience, it is them most of the time.  We have a lot of advertisers doing giveaways and such to their regulars.   

This is what I want  

![image](https://user-images.githubusercontent.com/82704096/136711467-91a9f38a-ed03-42ed-8f73-37a51a7e6d26.png)

Looking at this, we can see that Dayrogue wants to pay 50k balance himself.    so i had love it if i can just click his name and get userid

but right now i need to do the following

Discord --> dm's or Ctrl K  --> Find Dayrogue / or type Dayrogue (but he has weird name smh)  --> Right click him --> copy id

where a simply "click name to copy id" would be super simple.

**Comment by Wanhedaa** [comment]
i love this idea.

**Comment by DJDajn** [comment]
This has been implemented.
