### ISSUE TITLE
Discord auth token expire

### ISSUE THREAD

**Issue by Bgabor997** [Icecrown-Community/ICC-Member-Website-Public#16]
"we just need to increase the expiration token time. It's set to 24 hours atm, we can increase it to one week that will be fine.
Plus add a redirect from the /auth to / if he's authentificated"

**Comment by iElsha** [comment]
Allow user to be authenticated for 3 days instead of 1 day (auto-refresh is enabled)

**Comment by iElsha** [comment]
Can I get confirmation that it works properly now?

In addition we'll do https://github.com/Icecrown-Community/ICC-Member-Website-Public/issues/86

**Comment by TheAmazingTyr** [comment]
any chance for a settings menu while logging in to set the range, 1day 3 days 5 days 7 days?

**Comment by iElsha** [comment]
Not really
