### ISSUE TITLE
Duplicate, or absent submit

### ISSUE THREAD

**Issue by iElsha** [Icecrown-Community/ICC-Member-Website-Public#17]
Submitting curves encounter issues

:check: = submitted runs, some multiple times as noted
:no_entry_sign: = didnt get submitted

![image](https://user-images.githubusercontent.com/38140638/104191796-43e89480-541e-11eb-9867-2d5455ea8fcd.png)

**Comment by iElsha** [comment]
It seems that it only affects curves runs for now @Bgabor997 this is a high priority

**Comment by Bgabor997** [comment]
i think, there is no difference in submit for curve and full runs, i try to check something

**Comment by iElsha** [comment]
This should be fixed in PR https://github.com/Icecrown-Community/ICC-member-website/pull/70 and added more logs to identify the error faster
