### ISSUE TITLE
Improve gold collector system for raids

### ISSUE THREAD

**Issue by iElsha** [Icecrown-Community/ICC-Member-Website-Public#22]
- Add a gold collector note on each booking
- Add a gold collector button mooving from these states
          - Before GC step: "not collected" (default) to "collected" (back to "not collected)
          - During: "not collected" to "collected" to "submitted" (back to "not collected)
- Make the appropriate changes on the backend

**Buttons cycle**
![image](https://user-images.githubusercontent.com/38140638/104848358-e4d6c400-58e4-11eb-9313-d5b11141e4d2.png)

**Buttons icons**
XXX -> Collected : https://material.io/resources/icons/?search=check&icon=done&style=baseline
image

XXX - > Not collected : https://material.io/resources/icons/?search=x&icon=report&style=baseline
image

XXX - Sent : https://material.io/resources/icons/?search=check&icon=done_all&style=baseline
image

**Comment by Choppaaz** [comment]
- Add an extra button to mark the booster as took the boost or not and it should be as following: 

![image](https://user-images.githubusercontent.com/77581204/104848791-70595080-58f7-11eb-8ca0-7959497a77d8.png)

And the background of the booking to be colored as light green when marked as Boost done.

Icons as a suggestion: 
Ready for boost: https://material.io/resources/icons/?search=check&icon=unpublished&style=round 
Boost done: https://material.io/resources/icons/?search=check&icon=check_circle&style=round

**Comment by iElsha** [comment]
> * took the boost or not
He has been boosted or not

**Comment by iElsha** [comment]
https://user-images.githubusercontent.com/38140638/105414525-e4696080-5c37-11eb-9ca4-461d815b9b0f.mp4

This is the Gold collector major update that has been requested.
it also fixes https://github.com/Icecrown-Community/ICC-Member-Website-Public/issues/20

Regarding the background, is it better to have :
- red & green 
- default (grey) & green

**Comment by Tueri** [comment]
Grey and green. Red indicates an issue; normal steps in the process are not an issue.

**Comment by Dejnaa** [comment]
Looks nice, much approve

**Comment by Kairav93** [comment]
Red Green i prefer 👍

**Comment by Bgabor997** [comment]
> Grey and green. Red indicates an issue; normal steps in the process are not an issue.

exactly the same

**Comment by Choppaaz** [comment]
So once a customer is booked and the advertiser collects an amount (from 10% up to 100%), we want a field defining how much left to collect to avoid any miss calculation and to make it easier to track.

Its preferred to be like this inside the booking: 
![image](https://user-images.githubusercontent.com/77581204/104992372-f7aadf00-5a31-11eb-8859-574e8162a647.png)

Then from outside we want it to look like this (The missing gold in red color): 
![image](https://user-images.githubusercontent.com/77581204/104992708-a51df280-5a32-11eb-866f-42315143676b.png)

Adding those points here below: 
1- from inside booking the left or remaining amount should be unchangeable by anyone at all (protected).
2- from outside the booking the left or remaining amount (in red) shall disappear once full gold is collected and not showing in red with 0 amount

**Comment by Choppaaz** [comment]
If we can do that also please @iElsha

**Comment by Choppaaz** [comment]
> Grey and green. Red indicates an issue; normal steps in the process are not an issue.

Would agree on same thing, Gray and Green

**Comment by iElsha** [comment]
Alright, we've followed grey & green.

Regarding permissions, I've set up the following one:

     * See goldCollectionState (first Button): GC section & Managers section
     * See goldCollectionToDoState(second Button): GC section
     * See borders: GC & Managers & admin, plus advertiser = All except booster
     * See background: GC section

Thanks, everyone for your participation
