### ISSUE TITLE
Gluth to include GC pseudo when sending DM to customer

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/ICC-Member-Website-Public#23]
When Gluth sends a DM to the customer about who will collect their gold, the name appears as <@!240899740877848597>, because they have had no interaction with them other than seeing them in the sidebar. They would have to be able to see a channel that the GC typed in recently for this not to occur, so the DM should also include the pseudo of the person collecting.

**Comment by iElsha** [comment]
Alright, we'll add a name-realm just after

**Comment by iElsha** [comment]
![image](https://user-images.githubusercontent.com/38140638/105045549-53905a80-5a68-11eb-9738-1ef52819b44e.png)
The GC name has been added
