### ISSUE TITLE
Improve VIP limit system

### ISSUE THREAD

**Issue by iElsha** [Icecrown-Community/ICC-Member-Website-Public#24]
Instead of having one field limiting the number of vips, we should have 4 for each armor stack

**Comment by Suzaru** [comment]
We need a VIP system better than what we have at the moment. Experienced advertisers mentioned something [like this](https://i.imgur.com/bzsfITa.png)

**Comment by iElsha** [comment]
VIP systems has become really important, evenmore with the high number of raid. Our raid leaders and partners are struggling to communicate properly making us loose sales on this hence the severity increase.

**Comment by Suzaru** [comment]
Okay so, to refine the website and approach a v0.5 with the VIPs I suggest the following:

When creating/editing a raid you see [this line.](https://i.imgur.com/VvzsNSm.png) It is confusing and not enough. It can be removed fully. 
A better approach is [this](https://i.imgur.com/KPx6r1E.png). Beneath the Armor Classes (Plate/Mail/Leather/Cloth) add all Classes in general with a counter. Then we give the raidlead a "+" and "-" button similar [to this](https://i.imgur.com/0jnNsPt.png) so they can adjust the count for VIPs. That shouldn't be too hard.

Hard part will be a connection between this count and an advertiser booking something. It is imperative that when a raidlead specified they have "Cloth: 1" VIP available and Advertiser X books said cloth VIP that the count is reduced by 1, hence showing the correct remaining VIPs "Cloth: 0".

This would improve efficiency massively and would be a great approach that we always can improve later on.

PS.: I cba'd to put a "in my opinion" behind every sentence. Obviously this is only my perspective and feedback from advertisers.

**Comment by infinitypros** [comment]
its implemented
