### ISSUE TITLE
Show amount of gold needed to collect

### ISSUE THREAD

**Issue by Choppaaz** [Icecrown-Community/ICC-Member-Website-Public#29]
So once a customer is booked and the advertiser collects an amount (from 10% up to 100%), we want a field defining how much left to collect to avoid any miss calculation and to make it easier to track.

Its preferred to be like this inside the booking: 
![image](https://user-images.githubusercontent.com/77581204/104992372-f7aadf00-5a31-11eb-8859-574e8162a647.png)

Then from outside we want it to look like this (The missing gold in red color): 
![image](https://user-images.githubusercontent.com/77581204/104992708-a51df280-5a32-11eb-866f-42315143676b.png)

Adding those points here below: 
1- from inside booking the left or remaining amount should be unchangeable by anyone at all (protected).
2- from outside the booking the left or remaining amount (in red) shall disappear once full gold is collected and not showing in red with 0 amount

**Comment by iElsha** [comment]
>  Then from outside we want it to look like this (The missing gold in red color):
Wouldn't that be better to just have the remaining amount to collect displayed here?

**Comment by Bgabor997** [comment]
as i talked with Choppaa yesterday, its easier for Gold collectors when they edit the deposit, to see how much is remained, i suggested a disabled field here, what is just showing the difference. I can show you what i made and why

**Comment by iElsha** [comment]
Ok for a disabled field that's fine, plus the other one that he asked @Bgabor997.

You can do the PR when you have a chance

**Comment by iElsha** [comment]
![image](https://user-images.githubusercontent.com/38140638/105631010-6e8a1280-5e4c-11eb-9082-c9523f2e9870.png)
Result
