### ISSUE TITLE
Multiple bookings at the same time

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/ICC-Member-Website-Public#30]
We sometimes have the issue that we have multiple people  filling out their customers to book for a run and suddenly we are overfull. This is especially important during curve runs.

We also have to F5 the website all the time to see if something has been added.

- Could we add a 30-60sec automatic refresh to the site?

For Curve runs: 
- Could we add that the Raidleader sets how many customers are allowed in each run - for example 4 (it will then only allow 4 bookings on each boss for a specific time - so still allow 5 bookings if one is for generals and one is for Sire. (Note this is not the same as the Event amount of customers (normally 30?) that can be overbooked if agreed apon with RL)

![image](https://user-images.githubusercontent.com/77668716/105027296-e1138080-5a4f-11eb-9d71-7b97136cc9ef.png)

- Could we add that when you open a new Booking-form it chooses the earliest time available based on above? (atm it chooses the starting time of the raid)
![image](https://user-images.githubusercontent.com/77668716/105027411-01433f80-5a50-11eb-9de5-d1fc15ca0fcc.png)

- Could we add an undisplayed counter that keeps track of how many Booking-forms are currently open and only allows the Raidleaders amount of booking to be set for a specific time - automatically changing the time to the next run if 6 people open the Booking-Form "at the same time"?
![image](https://user-images.githubusercontent.com/77668716/105027520-2637b280-5a50-11eb-8040-f4671b514488.png)

- Also, if a customer gets cancelled, that time slot should come up again as someone opens the booking form (since the bosses now only have 3/4 customers booked at that time)

Above will make it possible to book our customers without having to speak to the other advertisers to not overbook a specific time and then have a debate who was first ect The advertisers can then also open a new booking and tell the customer that time right away.

Just my ideas

**Comment by iElsha** [comment]
> how many Booking-forms are currently open

This is not possible with the current architecture for technical reasons

---
> Also, if a customer gets canceled, that time slot should come up again as someone opens the booking form (since the bosses now only have 3/4 customers booked at that time)

This will be automated

**Comment by iElsha** [comment]
I split the other ideas into #31 #32 #34 and #35
