### ISSUE TITLE
Action to take when overpassing the customer limit

### ISSUE THREAD

**Issue by iElsha** [Icecrown-Community/ICC-Member-Website-Public#32]
The aim of this issue is to avoid this case 
![image](https://user-images.githubusercontent.com/38140638/105028997-0d300100-5a52-11eb-97fb-88416fe2e549.png)
where we have more customer booked than slot.

If I want to booked the `n+1` customer out of `n` slot, what should I get as feedback?

1. Error, you can't it's full
2. Warning, he's been added but you should reach the RL to be sure if he can handle him
3. Other suggestions?

**Comment by Dejnaa** [comment]
We want to be able to book over, as we sometimes get customers for 1 or 2 bosses in a full run, and the leader still wants to bring them as it makes the pot bigger. If we get 4 customers for 1 boss each (not the same one) the counter will still count them

If I had to pick I would say nr2
