### ISSUE TITLE
Horde/Alliance Banner

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/ICC-Member-Website-Public#33]
The Icons for Alliance and Horde are very small, and since the background picture is red-ish its easy to confuse the raids for Horde raids. Could we instead of a small Icon make a semi-transparent icon on the left side of the background picture?

Current:
![image](https://user-images.githubusercontent.com/77668716/105030048-7fedac00-5a53-11eb-96da-b1c223be4d12.png)

See example:
![image](https://user-images.githubusercontent.com/77668716/105030017-719f9000-5a53-11eb-9ff7-8f0419a7fbdb.png)
![image](https://user-images.githubusercontent.com/77668716/105030187-ba574900-5a53-11eb-8e61-7379c3a3711b.png)

**Comment by iElsha** [comment]
i'm really not a fan of this design, if someone comes with a proper change that still looks beautiful, we can change it.

This is the result with a 32px size instead of 24px
![image](https://user-images.githubusercontent.com/38140638/105039291-a9f99b00-5a60-11eb-9680-6090b87e74cb.png)

**Comment by Dejnaa** [comment]
As I said it was an example, didn't have access to the same picture, so just took one from google.

>  if someone comes with a proper change that still looks beautiful, we can change it.

Still look beautiful? I didn't realize this was about looks and not about being practical and easy for use.

If we are talking beauty, then the current one is mediocre at best. Guild Name, Difficulty, If its Full or not full run and time should be positioned in a more artistic way - Guild on top centered, Difficultly and full/not full run right under, time could be moved to next to or under the date.

No clue why there is a line both after Sire and under the Time, that does not look good at all. Gold mailing and all other phases could be shortened to only the icon, where you can see the full text of the phase when you go into the specific raid and look into the info tab. (in case someone have not learned how the different phases look) also while we are on this subject the Gold Mailing icon should me an envelope or coins, not a doctors chart/to do list. 

The Alliance logo on above picture is not inline with the text, and that triggers my artistic self. 
Yes, if we wanna talk feedback of looks I will have a lot to say :D

**Comment by iElsha** [comment]
> Still look beautiful? I didn't realize this was about looks and not about being practical and easy for use.

The idea is to fit a lot of data in a single place. That's hard to do and the best solution I came up with. We do care about being pratical more than beautiful that's why the #11 can also solve this issue a bit

---
In fact, elements are centered but on the image I did broke it a bit.

Shortening to the icon is not enough, you are used to the website but everyone isn't.

We might hire a UX/UI designer in the future if we want to improve these cards but that's not a priority atm.

**Comment by Wanhedaa** [comment]
what if we add this as alliance picture and the currently for horde? 
![image](https://user-images.githubusercontent.com/77633500/105061212-90b11880-5a79-11eb-8415-c22709f0eb54.png)

**Comment by iElsha** [comment]
Changing the background will be for showing different services in the same raid. That's what is planned atm.

**Comment by Dejnaa** [comment]
We dont really need a designer to fix majority of the visual "eye sores" I mentioned before

> Shortening to the icon is not enough, you are used to the website but everyone isn't.

No clue what you are trying to say with this :)

**Comment by Tueri** [comment]
The simple solution is adding [Horde] and [Alliance] at the front of each raid surely?

**Comment by Phenthex** [comment]
Well i prepared quick something like that maybe could work?

![image](https://user-images.githubusercontent.com/77830954/106019894-339a1000-60d4-11eb-8304-20845fdd1b4d.png)
![image](https://user-images.githubusercontent.com/77830954/106019930-3dbc0e80-60d4-11eb-89ad-d74a8c4fa936.png)

**Comment by iElsha** [comment]
what happens with the white border inside? 
1. Nothing
2. Outside the text
3. Outside Text + logo

**Comment by Phenthex** [comment]
On hover can be like that
![image](https://user-images.githubusercontent.com/77830954/106042598-50434180-60ee-11eb-93b7-c7c56a6b6376.png)
![image](https://user-images.githubusercontent.com/77830954/106042616-589b7c80-60ee-11eb-93ad-f0b0d0cf8c9a.png)

**Comment by Dejnaa** [comment]
I really like it! :D

Could you try putting the guild name over the run type? And the time under? Just would like to see how it looks with your example :)

![image](https://user-images.githubusercontent.com/77668716/106248990-0c495d00-6212-11eb-943c-c2058c4acbb2.png)
![image](https://user-images.githubusercontent.com/77668716/106249001-0fdce400-6212-11eb-95e5-d9e7e65d63c0.png)

**Comment by Phenthex** [comment]
Yay! Thank you im glad you liked it <3
I made your suggestion also, Guild Name / Inhouse Raid fonts are **bold** rest is regular, GC Name, Raid Leader Name-Realm and Raid Status fonts are _italic_.

**-  None active versions**

![image](https://user-images.githubusercontent.com/77830954/106299300-1137fc00-6266-11eb-94d4-8ae00c9500b9.png)

![image](https://user-images.githubusercontent.com/77830954/106299535-53f9d400-6266-11eb-9fd3-f253dfe92743.png)

**-  On hover versions**

![image](https://user-images.githubusercontent.com/77830954/106299811-b521a780-6266-11eb-9c31-017d6b489f40.png)

![image](https://user-images.githubusercontent.com/77830954/106299674-83104580-6266-11eb-8a1a-23258e65efdb.png)

**Comment by Dejnaa** [comment]
I really like it! Lets see what the others think ^^

**Comment by iElsha** [comment]
![casteNathria](https://user-images.githubusercontent.com/38140638/106431111-13b87280-646d-11eb-8d13-88c42e3ce788.jpg)

If you want the high res picture to make the change on it (red & blue) and send it here, we'll have a look when we come to that part

**Comment by Phenthex** [comment]
I edit the picture you send @iElsha
Here it how it looks ^^

![image](https://user-images.githubusercontent.com/77830954/106442664-98ff4f80-648c-11eb-8ebe-eae058c78bde.png)

**Comment by Dejnaa** [comment]
Could you make the background picture hue a bit brighter so more details are visable? If I was new in this thread I would have difficulty to see that this is Castle Natharia. Considering how small the pricture is I dont really see why we need to use this highres picture, the other one was easier to see.

**Comment by Phenthex** [comment]
Other picture i also used it had better quality + dimensions also were more high. But when i change hue of tha background, it loses exactly this blue & red color :(

**Comment by Dejnaa** [comment]
But if you put the blue/red on a different layer, and just alter the hue of the background picture then the blue and red hint shouldn't be affected :) Overall I give 1000 DKP for your pictures in this comment:

https://github.com/Icecrown-Community/ICC-Member-Website-Public/issues/33#issuecomment-769904207

Any other voters? Choppa?

**Comment by Phenthex** [comment]
Blue and red is not as overlayed layer. Its as smart filer/solid color and hue saturation change as filter again. And the other picture i used you linked it has better resolution thats why i can edit colors more on that. Pixel size /dpi is higher i mean. But in other image it has more low resolution so every change on colors i made as filter makes me to lose some details on darker colors.

**Comment by momos-icc** [comment]
Psssst, I'm going to drop this here :) Tried for a more streamlined, clear version. But as you can see the background gets a little bit lighter and the white box is around the edges for when it's hovered, and then of course red/blue backgrounds with a simple icon in the corner to make it super obvious for which faction.
![Raid-HoverStates](https://user-images.githubusercontent.com/5431885/107184358-07b93d00-69a6-11eb-9596-20ec53e642d4.gif)

**Comment by Phenthex** [comment]
Aaa yes please i really liked it clean and minimal <3

**Comment by Dejnaa** [comment]
I like it tooo a lot :D

**Comment by Dejnaa** [comment]
Did we get anywhere with this?
Such wonderful designs just getting forgotten - clean and minimalistic

But also like mentioned above in one of my posts, to put the "guild", run type and time on 3 different rows

Currently:
![image](https://user-images.githubusercontent.com/77668716/120907413-6d21ef80-c661-11eb-9622-8797f8205b7e.png)

It dont even fit the whole text. We could also add "end time" for curve shifts if we had more room

Like Phenthex showed so wonderfully:

![image](https://user-images.githubusercontent.com/77668716/120907429-a3f80580-c661-11eb-93cb-7b004d41ae3b.png)

**Comment by Dejnaa** [comment]
@Bgabor997 @momos-icc Thank you for this <3 <3 <3
