### ISSUE TITLE
Customer limit per shift

### ISSUE THREAD

**Issue by iElsha** [Icecrown-Community/ICC-Member-Website-Public#34]
This is from #30 
![image](https://user-images.githubusercontent.com/38140638/105029299-79ab0000-5a52-11eb-941c-509ba0a0ebc6.png)

**Comment by Dejnaa** [comment]
This can be closed - you made such an beautiful solution already:

![image](https://user-images.githubusercontent.com/77668716/120907456-dbff4880-c661-11eb-8b71-97292e60244b.png)
