### ISSUE TITLE
Show booster cut on signup page

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/ICC-Member-Website-Public#36]
Booster cut should calculate from total pot, adjusting with accpeted members. Currently this is calculated at 70% divided by booster count.

**Comment by iElsha** [comment]
The booster cut also depends based on the type of boost. I first wanted to implement automatic fetch from the cut database we have but that's a bit hard to achieve as we can't save a file on the website server. 

As the raid cut isn't changing anymore, we can rely on hardcoded values for this one but that will be an exception. We need to be warned if anything changes.

**What needs to be done**
-> Use the activities.json file to send cut information
-> Calculate and display it

**Comment by Dejnaa** [comment]
Is this a soon tm?

**Comment by iElsha** [comment]
This one is not in the plan for now

**Comment by DJDajn** [comment]
1

**Comment by Bgabor997** [comment]
This was deployed at 2021.10.02
