### ISSUE TITLE
Export Customer list with details into excel

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/ICC-Member-Website-Public#37]
Hello 

Currently its a bit user-unfriendly to manage the customers right in the website until we get the checks like Paid, Boosted, order of the bookings display, real time updating, ect

Would it be possible to have an export button that just exports all details to excel?

This is what I create each time I do curve runs to be able to keep track of all gold:

![image](https://user-images.githubusercontent.com/77668716/105159964-f6e87a80-5b0f-11eb-827f-ba1e16bdfc33.png)

**Comment by ICCDesi** [comment]
This should be somewhat easy to have a button ''export to .xlsx.''

Although with the improvements we are doing @Dejnaa i don't think this would be useful soon.

**Comment by Dejnaa** [comment]
depends how long it takes for all the abovementioned issues to be fixed ^^

**Comment by iElsha** [comment]
gold collection features should be here by Friday MAXIMUM

**Comment by iElsha** [comment]
Please, open this issue back if https://github.com/Icecrown-Community/ICC-Member-Website-Public/issues/22 doesn't fix it
