### ISSUE TITLE
Booster can't cancel the signup, until noone selected

### ISSUE THREAD

**Issue by Bgabor997** [Icecrown-Community/ICC-Member-Website-Public#41]
"Can't  unsign raids . After signing up for friday i tryed to unsign couse of plans changes . Today i seen i got accepted to boost so i DMed RL to remove me"

![image](https://user-images.githubusercontent.com/25648979/105388845-6e550180-5c17-11eb-889e-8e5d18acb43c.png)

**Comment by iElsha** [comment]
Is this related to https://github.com/Icecrown-Community/ICC-Member-Website-Public/issues/39 by anyway?

Did you succeed to reproduce the bug?

**Comment by Bgabor997** [comment]
hmm i don't know, Indig wants another thing i think

yes

nop, tried in open, running too
