### ISSUE TITLE
Send Raid date and time when confirming/removing booster signups (via Gluth)

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/ICC-Member-Website-Public#43]
As in title, they are only working with the ID and the link at the moment, can be confusing when signing for multiple raids.

**Comment by Dejnaa** [comment]
@Bgabor997 I am not a booster so cant check, but I do get date and what it is on other messages - has this been done already or still in the pipeline?

**Comment by Dejnaa** [comment]
@Tueri  serverity?

**Comment by Bgabor997** [comment]
- Add time for booster add/remove embeds ( yyyy-mm-dd h:i) (date functions: server/utils/String)
- Add the user display name to the submitRaid message ( who submited it)

**Comment by DJDajn** [comment]
1

**Comment by Bgabor997** [comment]
This was deployed at 2021.10.02
