### ISSUE TITLE
GC note visable by not assigned GC

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/ICC-Member-Website-Public#48]
Hey, I booked a customer today at a raid Orb was assigned to and I could see the GC note area.
I am not supposed to do that am I? :)

![image](https://user-images.githubusercontent.com/77668716/105558194-44cad180-5d0e-11eb-8bc0-c3a40aa2cdc7.png)

**Comment by Bgabor997** [comment]
Hmm, i think u see this one bcs u have the Gold Collector role, idk if we want this visible for the assigned GC only
Maybe Choppaa can answer for this.

**Comment by Dejnaa** [comment]
Yeah, I know that why I see it, but was thinking if I am supposed to see it :)
Because if I am not collecting for that raid, I am supposed to be "only an advertiser" even if I have the GC role :)

**Comment by ICCDesi** [comment]
The purpose of this was to be a tool to the assigned GC. Will move it into the enhancement section.

**Comment by Choppaaz** [comment]
It should be only visible to the assigned GC and me (as GC manager).
