### ISSUE TITLE
Suggestion: Automatic Gluth ping in #H/A-raid-announcements for upcoming raids

### ISSUE THREAD

**Issue by TheAmazingTyr** [Icecrown-Community/ICC-Member-Website-Public#52]
Make Suzu/Indigo/RL's jobs easier by automating the pings about incoming raids that are happening soontm (day or 2 ahead of time?)

Theoretically make it a weekly ping with schedules? maybe both?

**Comment by iElsha** [comment]
We have already started to talk about it with the advertiser managers & raid managers

**Comment by iElsha** [comment]
Closing as this is discussed somewhere else for now
