### ISSUE TITLE
Suggestion: Automatic Gluth ping for #general-announcements in advertiser zone

### ISSUE THREAD

**Issue by TheAmazingTyr** [Icecrown-Community/ICC-Member-Website-Public#53]
Make adv manager's jobs easier by automating "upcoming raids", either start of week, or day of, whatever they decide and "OH NO THERE'S A LACK OF BUYERS" 2-3 hours before the raid start IF under 50%/75% capacity? idk, up to adv managers. suggestion is there.

**Comment by iElsha** [comment]
Well, this is an advertiser manager job, but that could be possible in the future, really low low low prio as we already spoke about it but not required atm.

**Comment by Dejnaa** [comment]
I would say that I would not want this. 

Daily focus is there to help adv focus on the correct things - imagine getting 7 pings cause we havnt filled all Mythic raids 

Its better if the adv manager (me in this case) does 1 extra ping later in the day if its needed to get some action into the advs

I would say you can close this ticket
