### ISSUE TITLE
Gluth not sending any message

### ISSUE THREAD

**Issue by Bgabor997** [Icecrown-Community/ICC-Member-Website-Public#57]
Tyr, and Orb experienced it too

**Comment by iElsha** [comment]
As what I understood on Discord some are sent but not all when we have a high number of bookings, for curves runs especially.

We are going to remove GC discord messages as it's more a spam than useful due to the tons of bookings.

In exchange, we are going to add a "copy" button which will set into your clipboard the correct body mail

**Comment by iElsha** [comment]
Snippets for copy in clipboard with react hooks:
```js
import React, { useRef, useState } from 'react';

export default function CopyExample() {

  const [copySuccess, setCopySuccess] = useState('');
  const textAreaRef = useRef(null);

  function copyToClipboard(e) {
    textAreaRef.current.select();
    document.execCommand('copy');
    // This is just personal preference.
    // I prefer to not show the whole text area selected.
    e.target.focus();
    setCopySuccess('Copied!');
  };

  return (
    <div>
      {
       /* Logical shortcut for only displaying the 
          button if the copy command exists */
       document.queryCommandSupported('copy') &&
        <div>
          <button onClick={copyToClipboard}>Copy</button> 
          {copySuccess}
        </div>
      }
      <form>
        <textarea
          ref={textAreaRef}
          value='Some text to copy'
        />
      </form>
    </div>
  );
}
```
Source https://stackoverflow.com/questions/39501289/in-reactjs-how-to-copy-text-to-clipboard

**Comment by iElsha** [comment]
Will also solve https://github.com/Icecrown-Community/ICC-Member-Website-Public/issues/38

**Comment by Choppaaz** [comment]
I truly like this more, I mean a place to copy the info needed to send via mail. 
but how would we copy the message title then? 
As before we had both sent to us and with this copy feature it will include the message body only

**Comment by iElsha** [comment]
We can have two button, copy title & copy body?

**Comment by Bgabor997** [comment]
for this i have a suggestion: 
![image](https://user-images.githubusercontent.com/25648979/105631656-bcece080-5e4f-11eb-831a-2152661f1e6b.png)
We can display the title for copy below the buttons, i don't suggest the 2 button bcs the title is the same for every message

**Comment by iElsha** [comment]
The guy would need to scroll up each time, which's painful for booking in the end of the list

> for this i have a suggestion:
> ![image](https://user-images.githubusercontent.com/25648979/105631656-bcece080-5e4f-11eb-831a-2152661f1e6b.png)
> We can display the title for copy below the buttons, i don't suggest the 2 button bcs the title is the same for every message

**Comment by Choppaaz** [comment]
> We can have two buttons, copy title & copy body?

Then it would be better than before, as it would be easier this way.

**Comment by iElsha** [comment]
> > We can have two buttons, copy title & copy body?
> 
> Then it would be better than before, as it would be easier this way.

Elsha 1
Gabor 0

**Comment by Bgabor997** [comment]
I'm lost :( okay

**Comment by iElsha** [comment]
In order to avoid confusion as the icon will be the same for each button (AssignmentIcon), use different tooltips

**Comment by Bgabor997** [comment]
maybe we should use the filled for message and outlined for title too, some visual difference is good i think

**Comment by iElsha** [comment]
Or we can have this

Title Icon: 
![image](https://user-images.githubusercontent.com/38140638/105631770-66cc6d00-5e50-11eb-9f1e-de3a7d1e4aec.png)

Body icon: import AssignmentIcon from '@material-ui/icons/Assignment';

**Comment by Choppaaz** [comment]
![image](https://user-images.githubusercontent.com/77581204/105632565-dcdacf00-5e64-11eb-8216-871cf2a0cd80.png)
and 
![image](https://user-images.githubusercontent.com/77581204/105632567-e106ec80-5e64-11eb-82d5-3022bbd08740.png)
for me at least :)
