### ISSUE TITLE
Suggestion: Split "collected" button to "collected without deposit" and "collected deposit"

### ISSUE THREAD

**Issue by TheAmazingTyr** [Icecrown-Community/ICC-Member-Website-Public#59]
creates a clear line between "GC has 90%" and "GC has 100%". helpful for when/if deposit went missing, but not the full amount.

**Comment by Dejnaa** [comment]
You gave me an idea with this. We write all the numbers, easy to do a mistake. What if we write total amount 150,000 and have 2 buttons (in booking window) Collected Deposit and Collected All. Then Advertisers can click it for faster booking. If they picked 0 or a random number they can write it.

Then in the GC section, we could have Collected Deposit + Collected Customer (only shown if advertiser put an amount in deposit) and Collected all.
But this requires we have a GC collected field to enter the gold we collect and not to edit the deposit amount.

**Comment by iElsha** [comment]
Can you give more details if possible pls?

**Comment by TheAmazingTyr** [comment]
I'd like to separate the "collected" button into "collected from customer" and "collected from advertiser", simply because it gives more readability and clarity, as of now i have to use either a personal sheet or the GC notes which i have to open each dropdown menu for. Having a graphical showing of "you collected from customer, but not the deposit from adv" would make it a smoother thing to deal with at the gold mailing stage

**Comment by Bgabor997** [comment]
I doing it this way: only mark the booking as collected if i have all gold, so the red border shows me, where should i collect from advertisers, and when i collect 90%, i add it to the note, actually 3 click and a ctrl+v

**Comment by TheAmazingTyr** [comment]
Thats just not showing the rl what u collected and its literally the same amount of actions needed as my method.

**Comment by Winchester-Icc** [comment]
I was looking for this exactly. It's not that big of a deal but it bugs me too. Currently I'm using the "collected" button to help myself with collecting from advertisers after the curve shift is over.

Would it be possible to make it so advertiser types exact amount he collected and have a button for us "collected the rest" so we don't even edit advertiser's number. This way we know customer has fully paid and is ready to join the raid, but also we keep the red border as we have yet to collect the deposit from advertiser.

Again, not a big deal, but quality of life improvement.

**Comment by Choppaaz** [comment]
Let me explain their request @iElsha : 
![image](https://user-images.githubusercontent.com/77581204/107863023-0b473b00-6e62-11eb-8faf-fcfc47df8aea.png)
![image](https://user-images.githubusercontent.com/77581204/107863089-6ed16880-6e62-11eb-93c5-ab073a4ca9c8.png)
Where the Yellow gold is the deposit with advertiser, will make it much easier for GC to track what to collect

**Comment by TheAmazingTyr** [comment]
I personally hold a high prefference for simplicity and speed's sake to have that as a button on the card, not just on the edit screen. 

In choppa's design, i'd have the grey number represent the amount that is present on GC's char, red would be to collect from buyer, and yellow the deposit on the advertiser

Additionally, two buttons which would add their respective values to the value of the grey number, i.e. pressing the red check would add the "to be collected" to the collected amount, and make the border half yellow, other, yellow button would add the deposit to the value that GC has, and change the other half of the border from red to yellow

Visual clarity for GC and raid leaders alike, not increasing the amount of actions requred for the GC.

**Comment by iElsha** [comment]
It's QoL improvements with a very low prio'. Won't fix for now.

**Comment by Dejnaa** [comment]
Hey, in a different thread i made a suggestion for solving the payments being on different realms
Think if we add the GC section of collection it would really simplify to see what was collected by GC and what was collected by Adv

![image](https://user-images.githubusercontent.com/77668716/120907903-d6a3fd00-c665-11eb-9cf4-c0a26ce997e0.png)

On the card itself you could put that it shows the adv deposit only in GoldMailing mode, so that during raids when you just are collecting the customers you dont need to have so much extra numbers on each customer ticket - less likely to do mistakes

@Choppaaz what do you think?
