### ISSUE TITLE
Suggestion: Typebox with a copy button for Gold collector's quick introduction

### ISSUE THREAD

**Issue by TheAmazingTyr** [Icecrown-Community/ICC-Member-Website-Public#60]
Having a copied introduction and explanation why i am messaging people = good good, have it saved within personal GC sheet, would like to see it on the same page as where i copy buyer names, convenience, speed of GCing which gets hectic in large curves

**Comment by Dejnaa** [comment]
Hmm, if we could create a "signature" like setting on the website, then we could save our own text we wish to send to the customers - and then only 1-2 buttons could be added in the GC view for copy (like we have with the customer names)

Would this be "hard" to set up?

**Comment by ICCDesi** [comment]
I will close this issue since we have different plans for this one.
