### ISSUE TITLE
Suggestion: ability to click away bottom popups

### ISSUE THREAD

**Issue by TheAmazingTyr** [Icecrown-Community/ICC-Member-Website-Public#61]
Sometimes these popups, especially when 2 of them are present, tend to hide something, slight annoyance when GCing and trying to mark people only to get ****blocked by a success button

**Comment by iElsha** [comment]
What are these popups, can you provide a screenshot ?

**Comment by Dejnaa** [comment]
![image](https://user-images.githubusercontent.com/77668716/106898904-0c0aff00-66f5-11eb-8ac6-a633a7d75c02.png)
![image](https://user-images.githubusercontent.com/77668716/106899007-2644dd00-66f5-11eb-8cc1-b6951311299a.png)

These is what she is talking about. Its when we use the 2 new buttons for "Collected gold" "boost done"
