### ISSUE TITLE
Suggestion: If raid is marked as done (i.e. past running stage), and a buyer is not marked done, add "no show" button

### ISSUE THREAD

**Issue by TheAmazingTyr** [Icecrown-Community/ICC-Member-Website-Public#63]
would also be nice to have the gold button to copy 10% in this case, for sending deposit only, as we're keeping that in case of noshows.

**Comment by iElsha** [comment]
Not really sure why here?

**Comment by TheAmazingTyr** [comment]
Simplifying the pre-submitting check for the RL/Raid/curve manager. at the moment we either have to pray that it's in the note, or remember/go digging in DMs, plus between different GCs the border might be red (as uncollected due to noshow) or marked as yellow (collected cuz they have the deposit)
There are many variations to what people may do, having a standardised option to mark as a noshow (for the GC to mark) would make it way easier for the manager to find it and see oop, alrighty, this lad wasnt around, no dms needed, no searching or digging for gold. easy.

**Comment by iElsha** [comment]
Let's use adv & GC note for now - I understand the purpose but low prio and won't be fixed atm

**Comment by Dejnaa** [comment]
We have worked around this all this time and I dont feel like we need a no-show buttom. There is no GC that "would forget" that an unpaid customer didnt show up. Either the deposit was paid or it will be taken of the advertiser. 
 
@Wanhedaa what you think?

**Comment by Bgabor997** [comment]
we don't need this one, things changed a lot, and everything working without this
