### ISSUE TITLE
The ability to Group customers by payment realm

### ISSUE THREAD

**Issue by Choppaaz** [Icecrown-Community/ICC-Member-Website-Public#67]
I would be happy if there would be a way to sort customers by payment realm ( in gold mailing mode only ) as this will make it much easier than going in then out from each realm and sometimes you login on same realm more than 5 times :S 
This issue specially happens in curve runs and much needed there. 

For example, this run of mine got 39 customers on about 16-18 realm and it would be much easier if there is an option to sort them by payment realm when trying to send the gold: 
![image](https://user-images.githubusercontent.com/77581204/106001317-d9438400-60c0-11eb-9b9f-d6fa0f6eba13.png)

**Comment by Dejnaa** [comment]
TBH THIS emoji

**Comment by Dejnaa** [comment]
Same here, I do CTRL+F to search for a realm to make sure I send all gold with the correct Run IDs

If possible would be great if there was 1 button (All gold collected) that then organises all customers after payment realm (Goldmailing mode).

**Comment by ICCDesi** [comment]
This can be done once the raid is in "GC" Phase as Choppa said already. 

Added Labels & assigned it to the project.

**Comment by iElsha** [comment]
#84 duplicate
