### ISSUE TITLE
Managment view: buyers not marked as "sent" have an empty button that says Mark as "undefined"?

### ISSUE THREAD

**Issue by TheAmazingTyr** [Icecrown-Community/ICC-Member-Website-Public#71]
giga minor. just noting a small boop in the site

**Comment by iElsha** [comment]
Can you provide a SS pls?

**Comment by TheAmazingTyr** [comment]
I'll provide on tmrws boost

**Comment by TheAmazingTyr** [comment]
![Screenshot_1271](https://user-images.githubusercontent.com/77886383/107834910-0027d880-6d98-11eb-98e3-865ec6093565.png)
![Screenshot_1272](https://user-images.githubusercontent.com/77886383/107834913-01590580-6d98-11eb-9359-0001bd413c0c.png)
![Screenshot_1273](https://user-images.githubusercontent.com/77886383/107834914-01590580-6d98-11eb-80b3-287cdc0833ca.png)

The undefined button is present, clicking it sets the associated value to null, or undefined, which leads to irreversibly marking the boost as "uncollected" (unless i go back a stage)

**Comment by ICCDesi** [comment]
Is still still a thing? I never saw it for a long time. 

If not we will close the issue.
