### ISSUE TITLE
Suggestion: Value checking (comparing prices with bosses tagged)

### ISSUE THREAD

**Issue by TheAmazingTyr** [Icecrown-Community/ICC-Member-Website-Public#72]
Would - highlight people mistakingly marking wrong bosses (which happens way too much)
warn people if they are mispricing bosses (maybe integrate hot deals in a way?)
mistake margin about the usual 10%, +-. 

I understand this is actually a large techical thingy, so low prio

**Comment by Dejnaa** [comment]
If wont fix please close ticket
