### ISSUE TITLE
Spec not showing correctly in roster

### ISSUE THREAD

**Issue by Bgabor997** [Icecrown-Community/ICC-Member-Website-Public#74]
https://images-ext-1.discordapp.net/external/5IJrEisvB-Ngu34Zel7JjcxzEgzdgJlb1lqWw7VRo0g/https/i.gyazo.com/thumb/1200/0a895d1a2182f0459fd0e44deafb6618-png.jpg

When he is picked as a tank, he shown as a dps

**Comment by IndigoICC** [comment]
Bump 

We had FEW(!) cases of over-picking boosters :P 

It's a minor thing and can be combated by a double check.

**Comment by iElsha** [comment]
Fixed
