### ISSUE TITLE
Suggesstion: Button to copy RL/GC discord tag

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/ICC-Member-Website-Public#76]
Everytime I need to contact the raidleader that I dont normally talk to, I have to go to the ICC discord and search for the name manually - cant copy it from the picture - then find a post he/she did, jump to it and then rightclick the name and "Send Message". 

I think if the RL and GC had a invisible button over the name that copys their discord tagg it would be much faster to simply go to Discord and paste it into messages right away. Would be helpful for Raidleaders, Advertizers, GC and Boosters.

![image](https://user-images.githubusercontent.com/77668716/106456287-99e4b100-648d-11eb-9d6f-5caab187d213.png)

**Comment by TheAmazingTyr** [comment]
possibly expand into click to copy discord ID on hover? if you can be bothered, CSS animation or similar transition for some aesthetic transitions to correct width

**Comment by Dejnaa** [comment]
I was thinking of a "as little work as possible to just get it live" scenario as they have enough stuff to work with. 
Makes sense to just click on a name to get a discord tag, not needing any extra visuals. 

I dont know how much work your suggestion is compared to mine :)

**Comment by DruidEmmaNielsen** [comment]
Aight so I just figured we use github and wanted to share my opinions of this matter too. 

The GC/RL name is name we use on ICC Server, it is not the name they use on Discord.

Perfect example would be Winchester, who is Winchester on ICC Servers but has a Discord account of "Evil" 
so far i've not had issues finding him but when I have to dm raid leaders such as "Imahottie"  i have now figured out that i just need to search for "Hottie" but there are so many raid leaders who doesn't show up on Ctrl + K 

so as a tempoary solution, i am @ mentioning them in #community chat and then dm them from there.  My suggestion here would be if it would be possible the following things. 

1. It shows Discord name + we can click to copy name for instant Ctrl + k search
2. It shows name right now, but when click we get their discord user ID 
3. or we just get their handle "@name" example:  if someone clicked me it would be "@EmmaNielsen#0001"

**Comment by Wanhedaa** [comment]
We have a guild representatives channel where you can find every representative if it doesnt show up with searching on them. Else if you type the in game name, it should also show up.

The idea is great, i'd like to take it also, but even if you copy his name, and you never talked with him in the past few days, it will not show up :)

**Comment by Winchester-Icc** [comment]
I had trouble finding the guild representatives channel the other day, as I was in real hurry, took me 5+ minutes. It didn't show up in the search when I searched for it, nothing came up. Also trying to tag people in public chat (which I do even as raid leader when I need to invite/tag boosters I've picked for the raid, their name doesn't always show up until you spell it all the way, and some characters I can't find. That's why I got rid of my "è" although it's an easy one.

It would save you precious time in some cases. Having the person's full ICC nickname will at least let you tag him if he doesn't show up in the search to DM him.

It's not that often I have trouble with this, but for the long run I see it as big quality of life feature.

**Comment by Dejnaa** [comment]
I have issues with contacting the guild reps EVERY time. 
Its like I wrote in the top. We have such a sexy Customer name copy - can we please have the same for the Raidlead and GC?

**Comment by Dejnaa** [comment]
I think someone told me this was in the making, but its still not live - will we have it with the next "patch" of the website? 
It would help all advertisers that are trying to get a hold of RL or GC - which is often

Also, if we are at it, we could add it to adv names on the tickets aswell - to make it faster for GC's to message them about the gold collections.

**Comment by Dejnaa** [comment]
@Bgabor997 Thank you for this, you are an angle <3
