### ISSUE TITLE
Sort by server - gc option

### ISSUE THREAD

**Issue by Wanhedaa** [Icecrown-Community/ICC-Member-Website-Public#79]
My idea is, to be able to sort the customers by server. This would help the mail sending proccess, especially on curves

**Comment by Dejnaa** [comment]
Choppa already posted this suggestion :)

**Comment by Wanhedaa** [comment]
> Choppa already posted this suggestion :)

I dont see it actually, tried to search it

**Comment by Wanhedaa** [comment]
Didnt see sorry :D

**Comment by ICCDesi** [comment]
Duplicate of #67
