### ISSUE TITLE
New Raid Catagory needed

### ISSUE THREAD

**Issue by IndigoICC** [Icecrown-Community/ICC-Member-Website-Public#80]
VIP system is getting integrated into Curves. Today we had the first VIP in a curve shift, which essentially added another run on top of the original run (price wise). I would like for there to be a Catagory option called: "VIP - Curves", so that I'm eligible to throw together one SLG/Sire run in no time for VIP sales during any given reset.

**Comment by IndigoICC** [comment]
Also a "Custom" catagory ^^
We were getting interest in some BoD Transmog Runs (Catagory would be legacy), so the "Custom" name would be the best title for the catagory. Backround picture would be the Yogg-Sarons puzzle box:
Picture: https://gyazo.com/47987bbfa9a23880c6512613ea3bf266

**Comment by Bgabor997** [comment]
> Also a "Custom" catagory ^^
> We were getting interest in some BoD Transmog Runs (Catagory would be legacy), so the "Custom" name would be the best title for the catagory. Backround picture would be the Yogg-Sarons puzzle box:
> Picture: https://gyazo.com/47987bbfa9a23880c6512613ea3bf266

i like this idea, i give it a shot at the morning

**Comment by Bgabor997** [comment]
> VIP system is getting integrated into Curves. Today we had the first VIP in a curve shift, which essentially added another run on top of the original run (price wise). I would like for there to be a Catagory option called: "VIP - Curves", so that I'm eligible to throw together one SLG/Sire run in no time for VIP sales during any given reset.

If i understand i corrrectly, u need a "VIP-Curves" option to the Service select, right?

**Comment by IndigoICC** [comment]
> If i understand i corrrectly, u need a "VIP-Curves" option to the Service select, right?

To the Service indeed

**Comment by iElsha** [comment]
> VIP system is getting integrated into Curves. Today we had the first VIP in a curve shift, which essentially added another run on top of the original run (price wise). I would like for there to be a Catagory option called: "VIP - Curves", so that I'm eligible to throw together one SLG/Sire run in no time for VIP sales during any given reset.

Wouldn't just the note be enough for it, why do we need a full service just for it?

**Comment by IndigoICC** [comment]
The note will be enough, yep. Since VIPs for Curves will be done exclusively on Wednesdays, I no longer see a reason as to have another category within the "Service" option (later in any given tier, when everyone has stopped during Heroic within their guilds, we will then offer VIPs on demand). 

You can mark as resolved.

**Comment by Bgabor997** [comment]
@IndigoICC  if we maark it as resolved, do u mind creating a new issue about the legacy things, bcs we have something yet in that feature?

**Comment by IndigoICC** [comment]
Can do, Firefox.
