### ISSUE TITLE
After editing a booking, next time I edit it all available bosses are selected

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/ICC-Member-Website-Public#82]
Edited my booking - (this example The time shift) - Saved. This is how it looks:
![image](https://user-images.githubusercontent.com/77668716/106902889-9b1a1600-66f9-11eb-8c76-1ea177ce9b2b.png)

Click edit again after and it shows like this: 
![image](https://user-images.githubusercontent.com/77668716/106902919-a3725100-66f9-11eb-8875-a6bde3c4f033.png)

For curve only does it for the last 2, for full run does it for ALL bosses. Have caught myself doing this on curve runs many times, and had to change it back. Very easy to fuck up a booking if not paying attention. Had this problem when I was editing my Mythic customer for Huntsman only, and it selected ALL bosses.

**Comment by iElsha** [comment]
https://user-images.githubusercontent.com/38140638/107492355-a1424380-6b8c-11eb-8119-66fc73e4a414.mp4

**Comment by iElsha** [comment]
PR: https://github.com/Icecrown-Community/ICC-member-website/pull/122
