### ISSUE TITLE
Please make Name field remove Space

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/ICC-Member-Website-Public#83]
A couple of times each Curve shift, someone has added their customers name with a space after, so the name on the booking becomes Dejnaa -Sylvanas : When I then copy it to send a whisper it obviosly fucks it up - making me whisper the realm to Dejnaa, so if she is not on my server the message will not arrive. 

![image](https://user-images.githubusercontent.com/77668716/106903669-9144e280-66fa-11eb-88b0-cc77725533ed.png)

I edit peoples bookings so it dont happen next time when I copy that name, but a quick fix would be to not save spaces in the Name field.

**Comment by ICCDesi** [comment]
@Bgabor997 Maybe you could that quick

**Comment by Bgabor997** [comment]
Its done, because of another issue, already made the PR, that gonna solve both issue

**Comment by iElsha** [comment]
Done in https://github.com/Icecrown-Community/ICC-member-website/pull/107
