### ISSUE TITLE
Suggetion: Compress the information a bit on the Customer Cards

### ISSUE THREAD

**Issue by Dejnaa** [Icecrown-Community/ICC-Member-Website-Public#84]
We would be able to see many more customers on a page if we didnt use so much dead space between the different info. 
I made the browser as small as possible to see how much it will compress the cards - see picture, left is a normal customer as it is now - the right one I have compressed in paint just to show how much space can be saved.

![image](https://user-images.githubusercontent.com/77668716/106904535-9a827f00-66fb-11eb-87e5-4635cd31436f.png)

The width is good per card, but you could edit so we can have 5 cards on each line instead of max 4 :)
![image](https://user-images.githubusercontent.com/77668716/106905374-85f2b680-66fc-11eb-969e-6a8f27e73c36.png)

**Comment by iElsha** [comment]
We might be able to release a compact view mode in the future but it's not a priority

**Comment by Fakevox** [comment]
Crazy Suggestion make it bars going horizontal with the relevant information like the old spreadsheet....  Way easier to manage and work your way down the list etc.

Here's my mock-up

![Booking Idea](https://user-images.githubusercontent.com/78853011/107575603-fbbcbd80-6be7-11eb-8410-8a03d0b8a89f.png)

**Comment by Dejnaa** [comment]
This also looks really nice! Very handy and easy to see - I like!

**Comment by Winchester-Icc** [comment]
Looks good to me. Even lower height bars to fit more customers. And notes can be visible at all time.

**Comment by iElsha** [comment]
Style feature, a toggle button to activate ICC website in "Compact Theme"

**Comment by Dejnaa** [comment]
I am closing this one - THis was suposed to be a quality of life, but considering that other things with a higher Severity level also take 6 months + we always find new important things to focus on this will never happen. Just clutters the page.
