### ISSUE TITLE
Show done state for advertisers too

### ISSUE THREAD

**Issue by Bgabor997** [Icecrown-Community/ICC-Member-Website-Public#90]
show the background for advertisers too even on the "Anonymus bookings"

**Comment by iElsha** [comment]
Who requested it, and why?

**Comment by Bgabor997** [comment]
James, bcs he usually adding 20-30 customer under a Curve shift its very good for him and for other advertisers to know which run is done and how can he schedule the next customer

**Comment by iElsha** [comment]
Ok perfect
