### ISSUE TITLE
[Quality Of Life] Update boost message output to confirm bankname-realm.

### ISSUE THREAD

**Issue by Fakevox** [Icecrown-Community/ICC-Member-Website-Public#96]
Current Example of message posted to advertiser which is then copy pasted to the gold collector

RunId: 808878720394854450
Pot: 375,000
Activity: Dungeon M+
ActivityId: 0
Advertiser: Jamésdruid-Tarrenmill [Trainer]
AdvertiserId: 183286897823449088
Realm: doomhammer

Suggestion would be that it now does 

RunId: 808878720394854450
Pot: 375,000
Activity: Dungeon M+
ActivityId: 0
Advertiser: Jamésdruid-Tarrenmill [Trainer]
AdvertiserId: 183286897823449088
Realm: doomhammer

**Bank : Bankname-realm**

This new message is automatically generated by the bot based on the realm the gold was collected on to save the GC having to reference the sheet each time. Ensuring it's on a separate line as well so it's not copy pasted into the ingame mail.

This will also reduce errors on the user end as it's defined by the bot. Plus we get to copy paste it!

**Comment by Fakevox** [comment]
Wrong section #Hodor

**Comment by Choppaaz** [comment]
Looks good to help advertisers and GC not to miss the correct realm specially with connected realms 👍

**Comment by ICCDesi** [comment]
This issue is closed and has been transferred [Here!](https://github.com/Icecrown-Community/Icecrown-Precious-Bot-Public/issues/19)
